config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Une fois encore, tu dois avoir une idée précise des fonctionnalités de ton application pour créer tes routes.
  # Voici la liste des fonctionnalités :
  # Un utilisateur peut voir toutes les listes # GET "lists"
  # Un utilisateur peut voir les détails d’une liste donnée et son nom # GET "lists/42"
  # Un utilisateur peut créer une nouvelle liste # GET "lists/new"# POST "lists"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # couple list/movie ne peut apparaitre qu'une fois
  validates :list, uniqueness: { scope: :movie }

  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  # qd une liste est delete -> supp tous les bookmarks
  has_many :bookmarks, dependent: :destroy

  has_many :movies, through: :bookmarks

  has_one_attached :photo
  # list.movies

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    # @bookmark = Bookmark.find(params[:list])
    @list = List.find(params[:list_id])
    # raise
  end

  def create
    # chercher dans nos listes, l'id de la liste
    # /lists/7
    @list = List.find(params[:list_id])
    # creer new instance de bookmark avec des parametres
    @bookmark = Bookmark.new(bookmark_params)
    # lier avec la bonne list -> liste avec id 7, la lier avec le bookmark crée
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

    # save
    # @review = Review.new(review_params)
    # @review.restaurant = @restaurant

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

# Un utilisateur peut ajouter un nouveau signet (association film/liste) à une liste existante

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  # 1. new creer le formulaire
  def new
    @list = List.new
  end
  # 2. soummettre le formulaire
  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%# redirige vers method create %>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/vecteurs-libre/cinema-salle-theatre-pour-premier-film-design-affiche-chaises-dans-piece_1017-8728.jpg?size=626&ext=jpg&ga=GA1.1.979251218.1700233854&semt=ais);">
  <div class="container">
    <h1> Save any kind of movies</strong>!</h1>
    <a class="btn btn-flat" href="#"></a>
  </div>
</div>

<div class="container mt-4">
  <%= "MY LISTS" %>

  <div class= "d-flex justify-content-start mt-5">
    <ul>
     <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list), class:"text-decoration-none"%> </li>
      <%end%>
    </ul>
  </div>

  <div class="btn bg-success">
    <%= link_to 'create a movie list', new_list_path, style:"color:white"%>
  </div>

</div>


<%#
# utilisation de class, style
class = -> quand c'est du HTML
quand erb -> class:

style: ecrire du CSS dans le HTML
comme un hash avec clé:valeur
pareillement aurait pu mettre style= -> CSS mais moins pratique

# ajouter une image
suivre le setup active storage

# delete sur nos lists ? %>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1> <%= @list.name %> </h1>
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>

<% @list.bookmarks.each do |bookmark|%>
  <%= bookmark.movie.title %>
  <%= bookmark.comment %>
  <%= link_to "Delete",
    bookmark_path(bookmark),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<% end %>


<%# details de la liste: nom des films %>

<%= link_to 'add a movie', new_list_bookmark_path(@list) %></li>
<%= link_to 'go back to the list', lists_path %>